### ISSUE TITLE
有些问题想和你讨论下

### ISSUE THREAD

**Issue by EdXu** [godmoon/CppZooKeeperApi#1]
1. zhandle_t 是struct，Reconnect和外部应用调用时存在并发问题，仅靠 外部应用枷锁时无法解决的。是否考虑在程序中加入读写锁。
2. 存在丢通知的问题，按照事件必定会丢通知（例如在会话超时的那段时间内有数据变化，订阅无法通知到），所以建议采用 数据版本号，异常情况下（会话异常），比对本地与服务器的版本差异，继而得到发现丢失数据变化通知。

**Comment by godmoon** [comment]
感谢你的反馈，因为最近关注这个比较少，所以这么晚才回复你。
1、zhandle_t加锁的问题是可以的，这个API设计之初没有主线程调用zhandle_t的需求，之所以暴露出来，也只是为了系统初始化时可以做一些封装API没做的事情，之后几乎都是zk api线程在使用。如果有使用的场景，可以商量一下看看有没有什么好的方法。加锁是一方面，也可以选择不加锁的方式，比如让ZK线程来做你需要做的事情，这样也可以避免加锁。
2、API设计目的是用于服务发现，如果是重连，会去获得最新的数据并且通知上层应用，保证客户端和服务端的最终一致性。zk本身的机制也不能保证每次修改都发一个通知，这期间存在重注册的问题，即通知后到重注册期间，所有的更改不会通知，重注册的时候回去拉取最新数据，然后保证后续节点相应变更会通知。因此会话异常时，封装API会进行重连操作，这期间会重注册所有Watcher，注册的时候会获得最新数据。
